APPTarefas/Models/ErrorViewModel.cs
namespace APPTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

APPTarefas/Models/Tarefa.cs
namespace APPTarefas.Models
{
    public class Tarefa
    {
        //Nome da chave primária deve ser Nome da Classe + "Id".
        public int TarefaId { get; set; } //Id é a chave primária 
        public string? Titulo { get; set; }
        public string? Descricao { get; set; }
        public bool Concluida { get; set; }
    }
}

APPTarefas/Controllers/HomeController.cs
using System.Diagnostics;
using APPTarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace APPTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

APPTarefas/Controllers/TarefasController.cs
using APPTarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppTarefas.Controllers
{
    public class TarefasController : Controller
    {
        // Lista em memória(grava as informações apenas quando a aplicação está rodando)
        private static List<Tarefa> _tarefas = new List<Tarefa>();
        private static int _proximoId = 1;

        // GET: Tarefas
        public IActionResult Index()
        {
            return View(_tarefas); // Envia a lista de tarefas como parametro para a pagina Index.
        }

        // GET: Tarefas/Create
        // Get -> Metodo para "pegar" a pagina e exibir
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tarefas/Create
        [HttpPost] // Especifica que este método responde a requisições POST
        [ValidateAntiForgeryToken] // Protege contra ataques
        public IActionResult Create(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                // Atribui um ID único para a tarefa
                tarefa.TarefaId = _proximoId++;
                // Adiciona a tarefa à lista de tarefas (_tarefas)
                _tarefas.Add(tarefa);
                // Redireciona para a página Index
                return RedirectToAction("Index");
            }
            return View(tarefa);
        }

        // GET: Tarefas/Edit/1
        public IActionResult Edit(int id)
        {
            // var tarefa = _tarefas[id];  // Trabalhando com Lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);
        }

        // POST: Tarefas/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Tarefa tarefaAtualizada)
        {
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);

            tarefa.Titulo = tarefaAtualizada.Titulo;
            tarefa.Descricao = tarefaAtualizada.Descricao;
            tarefa.Concluida = tarefaAtualizada.Concluida;

            return RedirectToAction("Index");

        }

        // GET: Tarefas/Details/1
        public IActionResult Details(int id)
        {
            // var tarefa = _tarefas[id];  // Trabalhando com Lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);
        }


        // GET: Tarefas/Delete/1
        public IActionResult Delete(int id)
        {
            // var tarefa = _tarefas[id];  // Trabalhando com Lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);
        }

        // POST: Tarefas/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            if (tarefa != null)
            {
                _tarefas.Remove(tarefa);
            }
            return RedirectToAction("Index");
        }





    }
}

APPTarefas/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Página inicial";
}

	</<div class="container py-5">

	<div class="text-center mb-5">
		<h1 class="display-4 fw-bold"><i class="bi bi-list"></i> AppTarefas</h1>
		<p class="lead text-muted">Gerencie suas tarefas diárias, de uma forma simples e eficiente!</p>
		<a asp-controller="Tarefas" asp-action="Index" class="btn btn-outline-primary btn-lg MT-3">Ver minhas tarefas</a>
	</div>


	<div class="row text-center">

		<div class="col-12 col-md-4 mb-4">
			<div class="card shadow-sm h-100">
				<div class="card-body">
					<i class="bi bi-plus-circle display-4 text-primary mb-3"></i>
					<h5 class="card-title">Adicionar tarefa</h5>
					<p class="card-text ">
						Crie novas tarefas rapidamente, para não perder nenhuma atividade.
					</p>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-4 mb-4">
			<div class="card shadow-sm h-100">
				<div class="card-body">
					<i class="bi bi-check-circle display-4 text-success mb-3"></i>
					<h5 class="card-title">Marcar como Concluída</h5>
					<p class="card-text ">
						Mar1ques suas tarefas como concluídas, para manter o foco no que importa.
					</p>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-4 mb-4">
			<div class="card shadow-sm h-100">
				<div class="card-body">
					<i class="bi bi-trash display-4 text-danger mb-3"></i>
					<h5 class="card-title">Excluir tarefa</h5>
					<p class="card-text ">
						Remova tarefas que não são mais necessárias, de formas fácil.
					</p>
				</div>
			</div>
		</div>

	</div>



</div>

APPTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] </title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/APPTarefas.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-light navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-list"></i> APPTarefas</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Tarefas" asp-action="Index">Lista de Tarefas</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" asp-aea="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - APPTarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

APPTarefas/Views/Tarefas/Create.cshtml
@model APPTarefas.Models.Tarefa
@{
	ViewData["Title"] = "Cadastro de Tarefas";
}

<><h1>Nova tarefa</h1>
<form asp-action="Create" method="post">
	<div class="form-grouop">
		<label>Título</label>
		<input asp-for="Titulo" class="form-control" />
	</div>

	<div class="form-grouop">
		<label>Descrição</label>
		<textarea asp-for="Descricao" class="form-control">
			</textarea>
	</div>
	<button type="submit" class="btn btn-success">Salvar</button>
	<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary">Voltar</a>

</form>

APPTarefas/Views/Tarefas/Delete.cshtml
@model APPTarefas.Models.Tarefa
@{
	ViewData["Title"] = "Ecluir Tarefa";
}

<h1>Excluir Tarefa</h1>
<p>Tem certeza que deseja excluir a tarefa "<b>@Model.Titulo</b>"?</p>

<form asp-action="Delete" method="post">
	<input type="hidden" asp-for="TarefaId" />
	<button type="submit" class="btn btn-danger">Excluir</button>
	<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

APPTarefas/Views/Tarefas/Details.cshtml
@model APPTarefas.Models.Tarefa
@{
	ViewData["Title"] = "Detalhes da Tarefa";
}

<h1>Detalhes da Tarefa</h1>

<p><b>ID:</b> @Model.TarefaId</p>
<p><b>Título:</b> @Model.Titulo</p>
<p><b>Descrição:</b> @Model.Descricao</p>
<p><b>Conluída:</b> @(Model.Concluida ? "Sim" : "Não")</p>

<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary mt-3">Voltar</a>

APPTarefas/Views/Tarefas/Edit.cshtml
@model APPTarefas.Models.Tarefa
@{

	ViewData["Title"] = "Editar Tarefas";
}

<h1>Editar Tarefa</h1>
<form asp-action="Edit" method="post">
	<input type="hidden" asp-for="TarefaId" />
	<div class="form-group mb-3">
		<label>Título</label>
		<input asp-for="Titulo" class="form-control" />
	</div>

	<div class="form-group mb-3">
		<label>Descrição</label>
		<textarea asp-for="Descricao" class="form-control"></textarea>
	</div>

	<div class="form-group mb-3">
		<label>Concluída?</label>
		<input type="checkbox" asp-for="Concluida" />

	</div>


	<button type="submit" class="btn btn-success px-3">Salvar</button>

	<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary px-3">Voltar</a>
</form>

APPTarefas/Views/Tarefas/Index.cshtml
@model List<APPTarefas.Models.Tarefa>
@{
	ViewData["Title"] = "Lista de Tarefas";
}

<h1 class="display-4 fw-bold">Lista de Tarefas</h1>

<a class="btn btn-primary btn-lg" asp-controller="Tarefas" asp-action="Create">Nova Tarefa</a>

<table class="table table-bordered table-striped mt-3">
	<thead>
		<tr>
			<th>ID</th>
			<th>Título</th>
			<th>Concluída</th>
			<th>Ações</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var tarefa in Model)
		{
			<tr>
				<td>@tarefa.TarefaId</td>
				<td>@tarefa.Titulo</td>
				<td>@(tarefa.Concluida ? "Sim" : "Não")</td>
				<td>
					<a asp-controller="Tarefas" asp-action="Details" asp-route-id="@tarefa.TarefaId" class="btn btn-info btn-sm me-2">Detalhes</a>
					<a asp-controller="Tarefas" asp-action="Edit" asp-route-id="@tarefa.TarefaId" class="btn btn-warning btn-sm me-2">Editar</a>
					<a asp-controller="Tarefas" asp-action="Delete" asp-route-id="@tarefa.TarefaId" class="btn btn-danger btn-sm me-2">Excluir</a>
				</td>
			</tr>

		}

	</tbody>
</table>